---
arch: arm64
download:
  arm32:
    url: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2025-10-02
    image: 2025-10-01-raspios-trixie-armhf-lite.img.xz
  arm64:
    url: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2025-10-02
    image: 2025-10-01-raspios-trixie-arm64-lite.img.xz
mount_point: /media/pi
