---

Done in disk burn atm


- name: Copy over keyboard
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Apply keyboard configuration
  command: setupcon
  become: yes
