$ANSIBLE_VAULT;1.1;AES256
37343634633530323863326139333531616530323239373266663136653833333238663263663639
6461623361613663353337333939646131326432613333660a353934653038613737356538356233
63336266636236336333326432343038653861316262653833303162613162323865386266376639
3936386336613539360a666262323234643539613934303632663063636636643230326361396233
65323831313838396636333031373165336431656232323330633565373937343361623731663535
63323730316233393939313138393236663063356531316339653033663536666662323034356337
37383136383234653232363637366466663738326463366461303737663736366634626635643636
64616161383538643839
